captainVersion: 4

services:
	listmonk-db:
		image: postgres:13
		volumes:
			- listmonk-db-data:/var/lib/postgresql/data
		restart: always
		environment:
			POSTGRES_USER: 'listmonk'
			POSTGRES_PASSWORD: 'LKNUSeqFN8xFWG4bxVks3sWgGfbUrlwrNm1k6Q6IuYFNMUr5gAuk'
			POSTGRES_DB: 'listmonk'
		caproverExtra:
			notExposeAsWebApp: 'true'
	listmonk:
		environment:
			TZ: Etc/UTC
			LISTMONK_db__host: 'srv-captain--listmonk-db'
			LISTMONK_db__database: 'listmonk'
			LISTMONK_db__user: 'listmonk'
			LISTMONK_db__password: 'LKNUSeqFN8xFWG4bxVks3sWgGfbUrlwrNm1k6Q6IuYFNMUr5gAuk'
			LISTMONK_db__ssl_mode: 'disable'
			LISTMONK_app__admin_username: 'andnym'
			LISTMONK_app__admin_password: 'tGZCBHGgY3fmay22UMfE0Xg2Q2cyMQv7s0XJWpGAWUZslNA7wFf4'
			LISTMONK_app__address: 0.0.0.0:9000
		caproverExtra:
			containerHttpPort: 9000
			dockerfileLines:
				- FROM listmonk/listmonk:'v2.0.0'
				- CMD yes | ./listmonk --install --idempotent && ./listmonk
		volumes:
			- listmonk-data:/listmonk
		depends_on:
			- listmonk-db

